### ISSUE TITLE
Missing close brace?

### ISSUE THREAD

**Issue by paladin-t** [demianmnave/CML#10]
https://github.com/demianmnave/CML/blob/87a816620b25eb23f5630e386ba625732dd90547/cml/matrix/hadamard_product.h#L14

missing `}`.

**Comment by demianmnave** [comment]
Wow, I'm very sorry for missing this---I didn't see a notification from github!  I'll fix this ASAP.

**Comment by demianmnave** [comment]
Fixed in 261df52

**Comment by paladin-t** [comment]
good job, many thanks!
